name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master   # chạy khi push lên branch master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # dùng phiên bản stable mới nhất

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # token mặc định của GitHub Actions
          publish_dir: ./build/web                   # thư mục chứa file web sau khi build
          publish_branch: gh-pages                   # branch chứa nội dung deploy
